FROM node:18-alpine3.20 AS build

WORKDIR /wip/web

COPY package.json package-lock.json ./

RUN yarn install

COPY . .

RUN yarn build

FROM nginx:alpine

COPY --from=build /wip/web/dist /usr/share/nginx/html

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
