export const TitleLabels_en = {
    create: {
      ref: 'Reference',
      name: 'Offer name',
      description: 'Description',
      taches: 'Tasks',
      disponipility: 'Availability',
      place: 'Place',
      contrat: 'Contrat',
      profil: 'Profil',
      experience: " Number of experiences",
      prestation: 'Gross Salary (Ariary) *',
      type: "Type of offer",
    },
    advertisement: {
      name: 'Titled',
      description: 'Description',
      categorie: 'Advertising category',
      tarif: 'Duration of the tariff',
      date: 'Publication date',
      type: 'Type of advertising',
      price: 'Salary band',
      link: 'Link',
      contact: 'Contact',
      child: 'For audiences with child(ren) ?',
      activityArea: "Activity area",
      categoriePost: 'Category',
      hobby: 'Leisure and sport',
      age: "Targeted age group",
      image: 'Import file',
      pet: 'Pet',
      transport: 'Means of transport',
    },
    tender: {
      title: 'Title',
      detail: 'Detail',
      audience: 'Target',
      tarif: 'Duration of the tariff',
      date: 'Publication date',
    },
    titleLab: {
      visual_pub: 'Advertising visualization',
      visual_annonce: 'Viewing the classified ad',
      create_pub: 'Creation of new advertising',
      create_annonce: 'Creation of new classified ad',
      create_offer: "Creation of new call for tender",
      create_job: 'Creation of job offer',
    },
  };
  