export const TitleLabels = {
  create: {
    ref: 'Réference',
    name: 'Nom de l’offre',
    description: 'Description',
    taches: 'Les tâches',
    disponipility: 'Disponibilité',
    place: 'Lieu',
    contrat: 'Contrat',
    profil: 'Profil',
    experience: " Nombre d'éxperience",
    prestation: 'Salaire Brut (Ariary) *',
    type: "Type d'offre",
  },
  advertisement: {
    name: 'Intitulé',
    description: 'Description',
    categorie: 'Catégorie de publicité',
    tarif: 'Durée du tarif',
    date: 'Date de publication',
    type: 'Type de publicité',
    price: 'Tranche salariale',
    link: 'Lien',
    contact: 'Contact',
    child: 'Pour des audiences avec enfant(s) ?',
    activityArea: "Secteur d'activité",
    categoriePost: 'Catégorie',
    hobby: 'Loisir et sport',
    age: "Tranche d'âge ciblée",
    image: 'Importer fichier',
    pet: 'Animal de compagnie',
    transport: 'Moyen de locomotion',
  },
  tender: {
    title: 'Titre',
    detail: 'Détail',
    audience: 'Cible',
    tarif: 'Durée du tarif',
    date: 'Date de publication',
  },
  titleLab: {
    visual_pub: 'Visualisation de la publicité',
    visual_annonce: 'Visualisation de la petite annonce',
    create_pub: 'Création de nouvelle publicité',
    create_annonce: 'Création de nouvelle petite annonce',
    create_offer: "Création de nouvel appel d'offre",
    create_job: 'Création offre d’emploi',
  },
};
