export const activities = [
  { value: "administration_publique", label: "Administration publique" },
  { value: "agriculture", label: "Agriculture" },
  { value: "agroalimentaire", label: "Agroalimentaire" },
  { value: "architecture", label: "Architecture" },
  { value: "artisanat", label: "Artisanat" },
  { value: "assurance", label: "Assurance" },
  { value: "audiovisuel", label: "Audiovisuel" },
  { value: "banque", label: "Banque" },
  { value: "btp", label: "BTP (Bâtiment et Travaux Publics)" },
  { value: "collectivite_territoriale", label: "Collectivité territoriale" },
  { value: "communication", label: "Communication" },
  { value: "comptabilite", label: "Comptabilité" },
  { value: "conseil_coaching", label: "Conseil / Coaching" },
  { value: "construction", label: "Construction" },
  { value: "developpement_informatique", label: "Développement informatique" },
  { value: "distribution", label: "Distribution" },
  { value: "edition", label: "Édition" },
  { value: "education", label: "Éducation" },
  { value: "elevage", label: "Élevage" },
  { value: "energie", label: "Énergie" },
  { value: "environnement", label: "Environnement" },
  { value: "evenementiel", label: "Événementiel" },
  { value: "finance", label: "Finance" },
  { value: "formation", label: "Formation" },
  { value: "genie_civil", label: "Génie civil" },
  { value: "gardiennage", label: "Gardiennage" },
  { value: "humanitaire", label: "Humanitaire" },
  { value: "hygiene_nettoyage", label: "Hygiène / Nettoyage" },
  { value: "immobilier", label: "Immobilier" },
  { value: "import_export", label: "Import-export" },
  { value: "industrie", label: "Industrie" },
  { value: "informatique", label: "Informatique" },
  { value: "ingenierie", label: "Ingénierie" },
  { value: "innovation_technologique", label: "Innovation technologique" },
  { value: "journalisme", label: "Journalisme" },
  { value: "juridique", label: "Juridique" },
  { value: "logistique", label: "Logistique" },
  { value: "manutention", label: "Manutention" },
  { value: "marketing", label: "Marketing" },
  { value: "medias", label: "Médias" },
  { value: "mode", label: "Mode" },
  { value: "ong", label: "ONG" },
  { value: "pharmacie", label: "Pharmacie" },
  { value: "peche", label: "Pêche" },
  { value: "presse", label: "Presse" },
  { value: "production_industrielle", label: "Production industrielle" },
  { value: "publicite", label: "Publicité" },
  { value: "recrutement", label: "Recrutement" },
  { value: "recherche", label: "Recherche" },
  { value: "restauration", label: "Restauration" },
  { value: "ressources_humaines", label: "Ressources humaines" },
  { value: "sante", label: "Santé" },
  { value: "securite", label: "Sécurité" },
  { value: "services_a_la_personne", label: "Services à la personne" },
  { value: "services_aux_entreprises", label: "Services aux entreprises" },
  { value: "textile", label: "Textile" },
  { value: "tourisme", label: "Tourisme" },
  { value: "transport", label: "Transport" },
  { value: "urbanisme", label: "Urbanisme" },
  { value: "vente", label: "Vente" },
  { value: "web_digital", label: "Web & digital" },
  { value: "autres", label: "Autres" }
];