import { Dimensions, StyleSheet, Platform } from 'react-native';
import { COLORS, SIZES } from '../../resources/constants';
const winWidth = Dimensions.get('window').width;
const winHeight = Dimensions.get('window').height;

export const buttonsStyles = StyleSheet.create({
  boutonValider: {
    borderRadius: 8,
    minWidth: 140,
    marginRight: 0,
    marginLeft: 12,
    paddingLeft: 12,
    paddingRight: 12,
    shadowOffset: { width: 2, height: 6 },
    shadowColor: '#338554',
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 4,
  },
  buttonLoginContainer: {
    maxHeight: Platform.OS === 'web' ? 150 : 100,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 80,
    alignContent: 'center',
    alignSelf: 'center',
    justifyContent: 'space-around',
    maxWidth: '100%',
  },
  buttonLogin: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    flexGrow: 1,
    flexShrink: 1,
    maxWidth: 160,
    height: '100%',
    marginHorizontal: 10,
    marginBottom: Platform.OS !== 'web' ? 30 : 0,
  },

  displayCenterImageLogin: {
    height: 160,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    flex: 1,
    marginTop: 10,
    marginBottom: 10,
  },
  displayCenter: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    flex: 1,
    marginTop: 10,
    marginBottom: 10,
    height: 60,
    width: '100%',
  },
  displayCenterSubmit: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    alignSelf: 'center',
    flex: 1,
    marginTop: 10,
    marginBottom: 20,
    height: 60,
    maxWidth: 300,
  },
  displayCenterFlex: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    display: 'flex',
    marginTop: 10,
    marginBottom: 10,
    height: 120,
    flexDirection: 'row',
    width: '200',
  },
  displayCenterForget: {
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginTop: 10,
    marginBottom: 10,
    flex: 1,
  },
  displayCenterInscriptionImage: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    flex: 1,
    marginTop: 30,
    marginBottom: 10,
    height: 60,
  },
  displayCenterLoginBottom: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    flex: 1,
    marginTop: 0,
    marginBottom: 0,
    height: 40,
  },
  displayHorizontal: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingBottom: 40,
    paddingTop: 20,
    alignContent: 'center',
    height: winHeight * 0.1,
  },
  displayHorizontalNomarg: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
  },
  displaySpacedBtn: {
    width: 250,
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    alignContent: 'center',
  },
  displaySpacedBtween: {
    flexDirection: 'row',
    width: winWidth - 240,
    height: winWidth * 0.2,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginHorizontal: 'auto',
  },

  linkUnderline: {
    width: '100%',
    maxHeight: 80,
    justifyContent: 'center',
  },
  textUnderline: {
    alignSelf: 'center',
    fontSize: 14,
    fontWeight: '700',
    color: '#0088CC',
    textAlign: 'center',
    marginVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#0088CC',
    width: 136,
  },
  btnValiderOuterProfil: {
    width: 280,
    backgroundColor: '#0f579e',
    borderRadius: 30,
    height: 50,
    paddingHorizontal: 30,
    shadowColor: 'rgba(15, 87, 158, 0.9)',
    shadowOffset: {
      width: 1,
      height: 2,
    },
    shadowOpacity: 0.4,
    shadowRadius: 7,
    elevation: 5,
    marginVertical: 4,
  },
  btnAnnulerOuterProfil: {
    width: 250,
    backgroundColor: '#F9FCFF',
    borderRadius: 30,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: 'rgba(240, 244, 248, 0.875)',
    shadowColor: '#fafafa',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.01,
    shadowRadius: 0,
    elevation: 0,
    marginVertical: 4,
  },

  btnAnnulerOuter: {
    minWidth: 130,
    backgroundColor: '#ffffff',
    borderRadius: 8,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: '#BDBDBD',
    margin: 12,
    flexGrow: 0,
    flexShrink: 1,
  },
  btnAnnuler: {
    color: '#BDBDBD',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    paddingHorizontal: 0
  },

  btnTabWrapper: {
    marginVertical: 24,
    borderRadius: 30,
    flex: 1,
    height: 50,
    minHeight: 50,
    maxHeight: 50,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    backgroundColor: '#f2f2f2',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    justifyContent: 'center',
    alignItems: 'stretch',
    alignContent: 'stretch',
    marginHorizontal: 0,
  },
  btnTabOuter: {
    height: 50,
    borderRadius: 30,
    flex: 1,
    margin: 0,
    display: 'flex',
    paddingHorizontal: 5,
    width: '100%',
    color: '#fff',
  },
  btnTabOuterActive: {
    height: 50,
    borderRadius: 30,
    flex: 1,
    backgroundColor: '#0088CC',
    margin: 0,
    display: 'flex',
    width: '100%',
    paddingHorizontal: 5,
  },
  btnTabTxt: {
    fontSize: 14,
    color: '#828282',
    marginHorizontal: 0
  },
  btnTabTxtActive: {
    fontSize: 14,
    fontWeight: '700',
    color: '#FFFFFF',
    marginHorizontal: 0
  },
  ButtonGreenTxt: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1D5C42',
    marginHorizontal: 5
  },
  ButtonGreenNoText: {
    width: 40,
    height: 40,

    paddingHorizontal: 4,
    paddingVertical: 8,
    backgroundColor: 'rgba(240, 244, 248, 0.875)',
    borderRadius: 30,
    shadowColor: 'rgba(0, 0, 0, 0.06)',
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.001,
    shadowRadius: 10,
    elevation: 5,
    marginVertical: 10,
    flexDirection: 'row',
  },
  ButtonGreenImg: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
    marginHorizontal: 5,
  },
  logoStyleLogin: {
    maxHeight: 120,
    maxWidth: 240,
    marginHorizontal: 0,
    marginVertical: 10,
    flex: 1,
    resizeMode: 'contain',
  },

  /* STYLE ADDED */

  btnValider: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    paddingHorizontal: 4,
  },
  btnValiderWhite: {
    color: '#01129E',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    fontStyle: 'normal',
    paddingHorizontal: 4,
    lineHeight: 20,
  },
  btnValiderOuter: {
    margin: 12,
    minWidth: 130,
    backgroundColor: COLORS.secondary,
    borderRadius: 16,
    height: 50,
    maxHeight: 50,
    paddingHorizontal: 4,
    flexGrow: 1,
    flexShrink: 1,
    width: '100%',
  },
  btnDelete: {
    margin: 12,
    minWidth: 130,
    backgroundColor: COLORS.red_color,
    borderRadius: 16,
    height: 50,
    maxHeight: 50,
    paddingHorizontal: 4,
    flexGrow: 1,
    flexShrink: 1,
    width: '100%'
  },
  btnValiderOuterWhite: {
    margin: 12,
    minWidth: 130,
    backgroundColor: 'white',
    borderRadius: 16,
    height: 50,
    maxHeight: 50,
    paddingHorizontal: 4,
    flexGrow: 1,
    flexShrink: 1,
    borderColor: COLORS.secondary,
    borderWidth: 1,
    width: winWidth - 50,
  },
  bkg_socio: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: SIZES.radius,
    backgroundColor: COLORS.blue_back,
    width: 56,
    height: 56,
    paddingVertical: 20,
    marginHorizontal: 20,
  },
  /* Bouton WIP */
  titleSwitch: {
    color: COLORS.black,
    fontSize: SIZES.h3,
  },
});
