export const TitleLabels = {
    FindCriteria: {
        post: 'Poste souhaité',
        secteur: "Secteur d'activité",
        level: "Niveau d'étude",
        availability: "Disponibilité",
        transport: "Transport",
        Accommodated: "Logé ou non?",
        recommend: "Recommandé ou non?",
        contrat: "Contrat",
        country: "Pays",
        province: "Province",
        common: "Quartier ou Commune",
        experience: "Nombre d'année d'expérience",
        old_job: "Ancien Travail",
        old_business: "Ancienne Entreprise",
        country_wish:"Pays souhaité",
        province_wish:"Province souhaité",
        common_wish:"Quartier ou Commune souhaitée",
        langue: "Langue",
        sport: "Sports",
        center_interest:"Centre d'intérêt",
        info:'Infos personnelles',
        more: 'Plus de critère',
        pretension: "Salaire brut (Ariary)",
        other: "Autres",
        candidate_search:'Statut du candidat'
    }};